name: FTP Deploy
on:
  push:
    branches:
      - main # or main, depending on your default branch

jobs:
  ftp-deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          ftp-server: ftpupload.net
          ftp-username: IF0_35581398
          ftp-password: ${{ secrets.IF0_35581398 }}
